# -*- coding: utf-8 -*-
"""Modelo de embeddings e matriz de similaridade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ruCv3zG9e2ofs_iK4Nu_PjkrvkuJuYlk
"""

import pandas as pd
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity

print ('### MODELO DE MATRIZ DE SIMILARIDADE INICIADA ###\n')

# Palavras para análise
print ('Recebendo palavras para modelo de vetorização...\n')

word= 'exemplo'
words=['exemplo', 'demonstração']
while word != '':
    word= input('Digite a palavra ou aperte enter terminar: ')
    words.append(word)

if len(words) > 3:
  words.remove('exemplo')
  words.remove('demonstração')

# Carregar um modelo Transformer pré-treinado em várias línguas, incluindo o português.
# Este modelo é excelente para gerar embeddings de palavras e sentenças.
print('\nCarregando o modelo de transformer...\n')
model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

# Gerar os embeddings (vetores) para cada palavra
print('Gerando os embeddings...\n')
embeddings = model.encode(words)

# Calcular a matriz de similaridade de cossenos
print('Calculando a matriz de similaridade...\n')
similarity_matrix = cosine_similarity(embeddings)

# Criar um DataFrame do Pandas para visualização clara da tabela
# Arredondando os valores para 3 casas decimais para melhor leitura
print ('Criando dataframe para visualização da matriz de similaridade com pandas...\n')
df_similarity = pd.DataFrame(similarity_matrix, index=words, columns=words).round(3)

# Imprimir a tabela de similaridade
print("Tabela de Similaridade Semântica (Similaridade de Cossenos):")
print(df_similarity)